#!/bin/bash
KEYDIR="$HOME/.sign"
PRIVATE="$KEYDIR/private_ecdsa.pem"

if [ -f $PRIVATE ]
  then
    openssl pkeyutl -sign -in $1 -inkey $PRIVATE -out $1.sig
  else
    echo "ERROR: Private key not found.  Run 'sign_makekeys'."
fi
